// Action types to [filter] reducer
export const SET_SEARCH_TERM = "SET SEACH TERM VALUE";
export const SEARCH_TASK = "SEARCH TASK BY TERM VALUE";

export const SET_TASK_STATUS_FILTER = "SET STATUS OF THE TASK FOR FILTER";
export const FILTER_TASKS_BY_STATUS = "FILTER TASKS BY STATUS FOR FILTER";

export const SET_SORT_VALUE_FILTER = "SET SORT TERM TO STATUS TO FILTER";
export const SORT_TASKS_BY_VALUE = "SORT TASKS BY SORT VALUE TO FILTER";
